CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL,
    balance NUMERIC(12,2) NOT NULL DEFAULT 0,
    creation_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);